//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBuilding
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HomeBuildingEntities : DbContext
    {
        public HomeBuildingEntities()
            : base("name=HomeBuildingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConstructionContract> ConstructionContracts { get; set; }
        public virtual DbSet<ContractDescription> ContractDescriptions { get; set; }
        public virtual DbSet<MasterData> MasterDatas { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialUnit> MaterialUnits { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RunningNumber> RunningNumbers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UnitPrice> UnitPrices { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual DbSet<Withdraw> Withdraws { get; set; }
    
        public virtual ObjectResult<string> usp_get_document_number(string key, string prefix, Nullable<int> digit)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var prefixParameter = prefix != null ?
                new ObjectParameter("Prefix", prefix) :
                new ObjectParameter("Prefix", typeof(string));
    
            var digitParameter = digit.HasValue ?
                new ObjectParameter("Digit", digit) :
                new ObjectParameter("Digit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_get_document_number", keyParameter, prefixParameter, digitParameter);
        }
    
        public virtual ObjectResult<usp_get_contract_description_Result> usp_get_contract_description(string contractId)
        {
            var contractIdParameter = contractId != null ?
                new ObjectParameter("ContractId", contractId) :
                new ObjectParameter("ContractId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_contract_description_Result>("usp_get_contract_description", contractIdParameter);
        }
    
        public virtual ObjectResult<usp_get_contract_receipt_Result> usp_get_contract_receipt(string ownerName, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var ownerNameParameter = ownerName != null ?
                new ObjectParameter("OwnerName", ownerName) :
                new ObjectParameter("OwnerName", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_contract_receipt_Result>("usp_get_contract_receipt", ownerNameParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<usp_get_contract_withdraw_Result> usp_get_contract_withdraw(string contractId)
        {
            var contractIdParameter = contractId != null ?
                new ObjectParameter("ContractId", contractId) :
                new ObjectParameter("ContractId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_contract_withdraw_Result>("usp_get_contract_withdraw", contractIdParameter);
        }
    
        public virtual ObjectResult<usp_get_receipt_history_Result> usp_get_receipt_history(string receiptId)
        {
            var receiptIdParameter = receiptId != null ?
                new ObjectParameter("ReceiptId", receiptId) :
                new ObjectParameter("ReceiptId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_receipt_history_Result>("usp_get_receipt_history", receiptIdParameter);
        }
    }
}
