//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBuilding
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeBuildingEntities : DbContext
    {
        public HomeBuildingEntities()
            : base("name=HomeBuildingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConstructionContract> ConstructionContracts { get; set; }
        public virtual DbSet<ContractDescription> ContractDescriptions { get; set; }
        public virtual DbSet<MasterData> MasterDatas { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialUnit> MaterialUnits { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RunningNumber> RunningNumbers { get; set; }
        public virtual DbSet<UnitPirce> UnitPirces { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Withdraw> Withdraws { get; set; }
    }
}
