//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBuilding
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningNumber
    {
        public System.Guid Id { get; set; }
        public string Key { get; set; }
        public string Prefix { get; set; }
        public int StartNumber { get; set; }
        public int EndNumber { get; set; }
        public int CurrentNumber { get; set; }
        public int Digit { get; set; }
        public int Priority { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public int Sequence { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.Guid> DeletedById { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
